<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="AllRoutines.aspx.cs" Inherits="BG.View.AllRoutines" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <link rel="stylesheet" href="http://code.jquery.com/mobile/1.1.0/jquery.mobile-1.1.0.min.css" />
    <link href="Style.css" type="text/css" rel="stylesheet" />
    <link rel="stylesheet" href="themes/bg.min.css" />
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript">
    </script>
    <script src="FixPostback.js" type="text/javascript"></script>
    <script src="http://code.jquery.com/mobile/1.1.0/jquery.mobile-1.1.0.min.js" type="text/javascript">
    </script>
</head>
<body>
    <form id="form1" runat="server">
        <div data-role="page" id=" main" data-theme="a">
            <div data-role="header" role="banner" align="center">
                <h3>All routines</h3>
            </div>
            <div>
                <asp:GridView runat="server" AutoGenerateSelectButton="True" OnPageIndexChanging="GridviewAllRoutines_OnPageIndexChanging" AllowSorting="true" CellPadding="5" CellSpacing="5"
                    OnRowDataBound="GridviewAllRoutinesOnRowDataBound" OnRowDeleting="GridviewAllRoutinesOnRowDeleting" OnSorting="GridviewAllRoutines_Sorting"
                    AutoGenerateDeleteButton="True" OnSelectedIndexChanging="GridviewAllRoutinesOnSelectedChanging" ID="GridviewAllRoutines" AutoGenerateColumns="False"
                    DataKeyNames="Id" AllowPaging="True" ForeColor="#333333" GridLines="None">
                    <AlternatingRowStyle BackColor="White" />
                    <Columns>
                        <asp:BoundField HeaderText="Name" DataField="Name" />
                        <asp:BoundField HeaderText="Tasks" DataField="Activities.Count" />
                        <asp:BoundField HeaderText="Dates" DataField="Dates.Count" />
                        <asp:BoundField HeaderText="Route" DataField="Route.Name" SortExpression="Route" />
                        <asp:TemplateField HeaderText="Employee(s)">
                            <ItemTemplate>
                                <asp:Label runat="server" ID="LabelAllEmployeeToRoutine" />
                            </ItemTemplate>
                        </asp:TemplateField>
                    </Columns>
                    <EditRowStyle BackColor="#7C6F57" />
                    <FooterStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
                    <HeaderStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#666666" ForeColor="White" HorizontalAlign="Center" />
                    <RowStyle BackColor="#E3EAEB" />
                    <SelectedRowStyle BackColor="#C5BBAF" Font-Bold="True" ForeColor="#333333" />
                    <SortedAscendingCellStyle BackColor="#F8FAFA" />
                    <SortedAscendingHeaderStyle BackColor="#246B61" />
                    <SortedDescendingCellStyle BackColor="#D4DFE1" />
                    <SortedDescendingHeaderStyle BackColor="#15524A" />
                </asp:GridView>
            </div>
            <br />
            <div>
                <asp:Label runat="server" Visible="false" ForeColor="Red" ID="LabelAllRoutinesError" />
            </div>
            <br />
            <div id="divActivitiesToRoutine" runat="server" visible="false">
                <div>
                    <asp:Label runat="server" ID="LabelSelectedRoutineName" Font-Bold="True" />
                </div>
                <br />
                <div>
                    <asp:Label runat="server" Text="Activities" Font-Bold="True" ID="LabelSelectedRoutineActivities" /><br />
                    <asp:GridView runat="server" ID="GridviewSelectedRoutineTasks" CellPadding="5" CellSpacing="5" AllowSorting="true" AutoGenerateColumns="False" DataKeyNames="Id" AllowPaging="True"
                        OnPageIndexChanging="GridviewSelectedRoutineTasks_PageIndexChanging" OnRowDataBound="GridviewSelectedRoutineTasks_OnRowDataBound" OnSorting="GridviewSelectedRoutineTasks_Sorting"
                        ForeColor="#333333" GridLines="None">
                        <AlternatingRowStyle BackColor="White" />
                        <Columns>
                            <asp:BoundField HeaderText="Project" DataField="EconomicProject.Name" SortExpression="Project" />
                            <asp:BoundField HeaderText="Task" DataField="EconomicTasktype.Name" />
                            <asp:TemplateField HeaderText="Taken" SortExpression="Taken">
                                <ItemTemplate>
                                    <asp:Label runat="server" ID="LabelSelectedRoutineTaskTaken" Text='<%# Bind("IsUsed") %>' />
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Date and time taken">
                                <ItemTemplate>
                                    <asp:Label runat="server" ID="LabelSelectedRoutineTaskDateTaken" Text='<%# Bind("ActivityTaken") %>' />
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Employee">
                                <ItemTemplate>
                                    <asp:Label runat="server" ID="LabelSelectedRoutineTaskTakenBy" Text='<%# Bind("TakenBy.UserId") %>' />
                                </ItemTemplate>
                            </asp:TemplateField>
                        </Columns>
                        <EditRowStyle BackColor="#7C6F57" />
                        <FooterStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
                        <HeaderStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
                        <PagerStyle BackColor="#666666" ForeColor="White" HorizontalAlign="Center" />
                        <RowStyle BackColor="#E3EAEB" />
                        <SelectedRowStyle BackColor="#C5BBAF" Font-Bold="True" ForeColor="#333333" />
                        <SortedAscendingCellStyle BackColor="#F8FAFA" />
                        <SortedAscendingHeaderStyle BackColor="#246B61" />
                        <SortedDescendingCellStyle BackColor="#D4DFE1" />
                        <SortedDescendingHeaderStyle BackColor="#15524A" />
                    </asp:GridView>
                </div>
                <br />
                <div>
                    <asp:Label runat="server" ForeColor="Red" ID="LabelActivitiesError" Visible="false" />
                </div>
                <div>
                    <asp:Label runat="server" ID="LabelSelectedRoutineAssociatedEmployeesLabel" Text="Associated employee(s)" Font-Bold="True" /><br />
                    <asp:Label runat="server" ID="LabelSelectedRoutineAssociatedEmployees" />
                </div>
                <br />
                <div>
                    <asp:Label runat="server" ID="LabelSelectedDatesLabel" Text="Dates" Font-Bold="true" /><br />
                    <asp:Label runat="server" ID="LabelSelectedDatesFromLabel" Text="From:" />
                    <asp:Label runat="server" ID="LabelSelectedDatesFrom" /><br />
                    <asp:Label runat="server" ID="LabelSelectedDatesToLabel" Text="To:" />
                    <asp:Label runat="server" ID="LabelSelectedDatesTo" />
                </div>
                <br />
                <div>
                    <asp:Button runat="server" ID="ButtonSelectedRoutineClose" Text="OK" OnClick="ButtonSelectedRoutineClose_Click" data-icon="check" />
                </div>
            </div>
            <br />
            <div>
                <asp:Button runat="server" Text="Manage selected routine" ID="ButtonManageRoutine" OnClick="ButtonManageRoutine_Click" Enabled="false" />
            </div>
            <br />
            <div id="divManageSelectedRoutine" runat="server" visible="false">
                <h4>Dates</h4>
                <div>
                    <asp:Label runat="server" Text="From: " ID="LabelSelectedRoutineFromLabel" Font-Bold="true" />
                    <asp:Label runat="server" Text="" ID="LabelSelectedRoutineFrom" /><br />
                    <asp:Button runat="server" Text="Change" ID="ButtonSelectedFrom" OnClick="ButtonSelectedFrom_OnClick" Enabled="false" />
                </div>
                <div>
                    <asp:Label runat="server" Text="To: " ID="LabelSelectedRoutineToLabel" Font-Bold="true" />
                    <asp:Label runat="server" Text="" ID="LabelSelectedRoutineTo" /><br />
                    <asp:Button runat="server" Text="Change" ID="ButtonSelectedTo" OnClick="ButtonSelectedTo_OnClick" Enabled="false" />
                </div>
                <br />
                <div id="divCalendar" runat="server" visible="false">
                    <div>
                        <asp:Calendar runat="server" ID="CalendarAllRoutines" OnSelectionChanged="CalendarAllRoutines_SelectionChanged">
                            <WeekendDayStyle ForeColor="yellowgreen" />
                            <SelectedDayStyle ForeColor="green" />
                        </asp:Calendar>
                    </div>
                    <div id="divCalendarError" runat="server">
                        <asp:Label runat="server" ForeColor="Red" ID="LabelCalendarError" />
                    </div>
                </div>
                <br />
                <div id="divManageEmployees" runat="server" visible="false">
                    <h4>Employee</h4>
                    <div>
                        <asp:DropDownList runat="server" ID="DropdownlistAllEmployees" AutoPostBack="true" OnSelectedIndexChanged="DropdownlistAllEmployees_SelectedIndexChanged" />
                    </div>
                    <div>
                        <asp:GridView runat="server" ID="GridviewAssociatedEmployees" PageSize="3" AutoGenerateDeleteButton="True" DataKeyNames="Id" AutoGenerateColumns="False"
                            CellPadding="4" ForeColor="#333333" GridLines="None" OnRowDeleting="GridviewAssociatedEmployees_RowDeleting">
                            <AlternatingRowStyle BackColor="White" />
                            <Columns>
                                <asp:BoundField HeaderText="Employee" DataField="Username" />
                            </Columns>
                            <EditRowStyle BackColor="#7C6F57" />
                            <FooterStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
                            <HeaderStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
                            <PagerStyle BackColor="#666666" ForeColor="White" HorizontalAlign="Center" />
                            <RowStyle BackColor="#E3EAEB" />
                            <SelectedRowStyle BackColor="#C5BBAF" Font-Bold="True" ForeColor="#333333" />
                            <SortedAscendingCellStyle BackColor="#F8FAFA" />
                            <SortedAscendingHeaderStyle BackColor="#246B61" />
                            <SortedDescendingCellStyle BackColor="#D4DFE1" />
                            <SortedDescendingHeaderStyle BackColor="#15524A" />
                        </asp:GridView>
                    </div>
                    <div>
                        <asp:Label runat="server" ForeColor="Red" ID="LabelEmployeesError" />
                    </div>
                </div>
                <br />
                <div runat="server" id="divActivities">
                    <h4>Activities</h4>
                    <div>
                        <table>
                            <tr>
                                <td>
                                    <asp:Label runat="server" Text="Project " />
                                </td>
                                <td>
                                    <asp:DropDownList runat="server" ID="DropdownlisAllProjects" AutoPostBack="true" OnSelectedIndexChanged="DropdownlisAllProjects_SelectedIndexChanged" />
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <asp:Label runat="server" Text="Task type" />
                                </td>
                                <td>
                                    <asp:DropDownList runat="server" ID="DropdownlistAllTaskTypesForProject" />
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <asp:Label runat="server" Text="Hours" />
                                </td>
                                <td>
                                    <asp:DropDownList runat="server" ID="DropdownlistHours" />
                                </td>
                                <td>
                                    <asp:DropDownList runat="server" ID="DropdownlistMinutes" />
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <asp:Button runat="server" ID="ButtonAddActivityToRoutine" Text="Add" data-icon="push" OnClick="ButtonAddActivityToRoutine_Click" />
                                </td>
                                <td>
                                    <asp:Button runat="server" ID="ButtonUpdate" Text="Update" data-theme="e" data-icon="refresh" OnClick="ButtonUpdateActivity_Click" Enabled="false" />
                                </td>
                            </tr>
                            <tr>
                                <td colspan="3">
                                    <asp:Label runat="server" ID="LabelErrorActivity" ForeColor="Red" />
                                </td>
                            </tr>
                        </table>
                    </div>
                    <br />
                    <div>
                        <asp:GridView runat="server" ID="GridviewAllActivitiesForRoutine" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" CellPadding="4" ForeColor="#333333" GridLines="None"
                            AutoGenerateSelectButton="true" OnRowDeleting="GridviewAllActivitiesForRoutine_RowDeleting" OnSelectedIndexChanging="GridviewAllActivitiesForRoutine_SelectedIndexChanging" DataKeyNames="Id">
                            <AlternatingRowStyle BackColor="White" />
                            <Columns>
                                <asp:BoundField HeaderText="Project" DataField="EconomicProject.Name" />
                                <asp:BoundField HeaderText="Task type" DataField="EconomicTaskType.Name" />
                                <asp:BoundField HeaderText="Hours" DataField="Minutes" />
                            </Columns>
                            <EditRowStyle BackColor="#7C6F57" />
                            <FooterStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
                            <HeaderStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
                            <PagerStyle BackColor="#666666" ForeColor="White" HorizontalAlign="Center" />
                            <RowStyle BackColor="#E3EAEB" />
                            <SelectedRowStyle BackColor="#C5BBAF" Font-Bold="True" ForeColor="#333333" />
                            <SortedAscendingCellStyle BackColor="#F8FAFA" />
                            <SortedAscendingHeaderStyle BackColor="#246B61" />
                            <SortedDescendingCellStyle BackColor="#D4DFE1" />
                            <SortedDescendingHeaderStyle BackColor="#15524A" />
                        </asp:GridView>
                    </div>
                </div>
                <div>
                    <asp:Button runat="server" Text="Accept changes" ID="ButtonSelectedRoutineOk" OnClick="ButtonSelectedRoutineAcceptChanges_Click" data-inset="true" Enabled="false" data-icon="check" />
                </div>
                <br />
                <div id="divReusableRoutineButton" runat="server" visible="false">
                    <asp:Button runat="server" ID="ButtonSelectedRoutineReuse" OnClick="ButtonSelectedRoutineReuse_Click" Enabled="false" />
                </div>
                <br />
            </div>
            <div>
                <asp:Button runat="server" Text="Back to admin page" data-icon="back" ID="ButtonBackToAdmin" OnClick="ButtonBackToAdmin_Click" />
            </div>
        </div>
    </form>
</body>
</html>
